#!/usr/bin/env python3
"""
Run Lighthouse performance audits against the live o7.am site and write a summary report.
Requires: Node/npx and Chrome/Chromium (for Lighthouse).
Usage: from repo root, run:  uv run python scripts/run-performance-audit.py
       or:  just perf
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "docs"
# Use www so Lighthouse doesn't count the o7.am → www redirect (~1s penalty)
LIVE_BASE = "https://www.o7.am"

# Pages to audit: (label, path)
PAGES = [
    ("Homepage", ""),
    ("Contact (with map)", "/contact.html"),
]


def run_lighthouse(url: str, out_path: Path) -> dict | None:
    """Run Lighthouse against url; save JSON to out_path. Returns parsed JSON or None on failure."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "npx",
        "--yes",
        "lighthouse",
        url,
        "--output=json",
        "--output-path=" + str(out_path),
        "--chrome-flags=--headless=new --no-sandbox",
        "--only-categories=performance",
        "--quiet",
    ]
    try:
        subprocess.run(cmd, cwd=REPO_ROOT, check=True, capture_output=True, text=True, timeout=120)
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired) as e:
        print(f"Lighthouse failed for {url}: {e}", file=sys.stderr)
        return None
    if not out_path.exists():
        return None
    with open(out_path, encoding="utf-8") as f:
        return json.load(f)


def extract_metrics(lhr: dict) -> dict:
    """Extract performance score and core metrics from Lighthouse result."""
    out = {}
    cats = lhr.get("categories") or {}
    perf = cats.get("performance") or {}
    out["score"] = perf.get("score")
    if out["score"] is not None:
        out["score"] = round(out["score"] * 100)

    audits = lhr.get("audits") or {}
    # LCP (ms)
    lcp = audits.get("largest-contentful-paint")
    if lcp and "numericValue" in lcp:
        out["LCP_ms"] = round(lcp["numericValue"])
    # CLS
    cls = audits.get("cumulative-layout-shift")
    if cls and "numericValue" in cls:
        out["CLS"] = round(cls["numericValue"], 3)
    # TBT (ms)
    tbt = audits.get("total-blocking-time")
    if tbt and "numericValue" in tbt:
        out["TBT_ms"] = round(tbt["numericValue"])
    # INP (ms) or FID
    inp = audits.get("interaction-to-next-paint") or audits.get("first-input-delay")
    if inp and "numericValue" in inp:
        out["INP_ms"] = round(inp["numericValue"])
    # FCP (ms)
    fcp = audits.get("first-contentful-paint")
    if fcp and "numericValue" in fcp:
        out["FCP_ms"] = round(fcp["numericValue"])
    return out


def write_report(results: list[tuple[str, str, dict | None]], report_path: Path) -> None:
    """Write docs/performance-report.md from list of (label, url, metrics)."""
    lines = [
        "# Performance audit — o7.am",
        "",
        "Generated by `scripts/run-performance-audit.py` (run with `just perf`).",
        "Requires Chrome/Chromium and Node/npx.",
        "",
        "## Live site",
        "",
        f"**Base URL:** {LIVE_BASE}",
        "**Tool:** Lighthouse (CLI), performance category only.",
        "*(Audit uses www so the o7.am→www redirect is not counted.)*",
        "",
        "## Results",
        "",
    ]
    for label, url, metrics in results:
        lines.append(f"### {label}")
        lines.append("")
        lines.append(f"- **URL:** {url}")
        if metrics:
            score = metrics.get("score")
            lines.append(f"- **Performance score:** {score}/100" if score is not None else "- **Performance score:** —")
            if metrics.get("LCP_ms") is not None:
                lines.append(f"- **LCP:** {metrics['LCP_ms']} ms")
            if metrics.get("CLS") is not None:
                lines.append(f"- **CLS:** {metrics['CLS']}")
            if metrics.get("TBT_ms") is not None:
                lines.append(f"- **TBT:** {metrics['TBT_ms']} ms")
            if metrics.get("INP_ms") is not None:
                lines.append(f"- **INP:** {metrics['INP_ms']} ms")
            if metrics.get("FCP_ms") is not None:
                lines.append(f"- **FCP:** {metrics['FCP_ms']} ms")
        else:
            lines.append("- *Audit failed or not run.*")
        lines.append("")
    lines.extend([
        "## Improvement ideas",
        "",
        "1. **LCP:** Preload key hero image or font if they block LCP; ensure images have width/height to avoid CLS.",
        "2. **CLS:** Reserve space for map iframe and any dynamic content; avoid inserting content above existing content.",
        "3. **TBT:** Defer or reduce non-critical JS; keep theme script minimal so it doesn’t block main thread.",
        "",
        "## Next quick wins",
        "",
        "See **[performance-correction-plan.md](performance-correction-plan.md)** § 7 for prioritised next steps: (1) make `style.css` non-blocking, (2) defer analytics, (3) map container min-height, (4) optional font preload.",
        "",
        "---",
        "",
        "*Re-run `just perf` to refresh this report.*",
    ])
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    results = []
    for label, path in PAGES:
        url = LIVE_BASE.rstrip("/") + ("/" + path.lstrip("/") if path else "/")
        slug = "home" if not path else path.replace("/", "-").strip("-").removesuffix(".html")
        json_path = OUT_DIR / f"lighthouse-{slug}.json"
        print(f"Auditing {label} ({url}) ...")
        lhr = run_lighthouse(url, json_path)
        metrics = extract_metrics(lhr) if lhr else None
        results.append((label, url, metrics))
        if metrics:
            print(f"  Score: {metrics.get('score', '—')}/100")

    report_path = OUT_DIR / "performance-report.md"
    write_report(results, report_path)
    print(f"Report written to {report_path}")
    return 0 if any(r[2] for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
